"""Generate data/reference/rules/{season}.yaml for seasons before 2026.

Decision (2026-09-29): the at-large standards printed in a season's Tri-Valley Hy-Tek
results are the source for that season's Area -> MOC at-large table. Everything else
(allocation numbers, league splits, Class A league standards, 4x800 system) is copied
from 2026.yaml and labelled "assumed from 2026". 2023 printed no standards, so it uses
the 2026 table labelled "assumed from 2026 — no printed source".

Each generated standard is {mark, source} so the provenance travels with the number.
"""

from __future__ import annotations

import copy
import re
from pathlib import Path

import yaml

from . import paths
from .events import parse_event

ASSUMED = "assumed from 2026"
ASSUMED_NO_SOURCE = "assumed from 2026 — no printed source"
PRINTED = "printed in results"
SEASONS = (2019, 2022, 2023, 2024, 2025)

_TITLE = re.compile(r"^(?:Event\s+\d+\s+)?(Girls|Boys)\s+(.+?)\s*$")
_AT_LARGE = re.compile(r"^\s*(\S+)\s+NCS At[- ]Large\s*$")


def printed_standards(text: str) -> dict[str, dict[str, str]]:
    """{gender: {event_code: mark as printed}} from "NCS At-Large" lines in Hy-Tek text."""
    out: dict[str, dict[str, str]] = {"girls": {}, "boys": {}}
    gender = code = None
    for line in text.splitlines():
        m = _TITLE.match(line)
        if m and not line.startswith(" "):
            info = parse_event(m.group(2))
            ok = info.code and not info.is_adaptive and info.modifier is None
            gender, code = (m.group(1).lower(), info.code) if ok else (None, None)
            continue
        m = _AT_LARGE.match(line)
        if m and gender and code:
            if code in out[gender] and out[gender][code] != m.group(1):
                raise ValueError(f"two different standards for {gender} {code}")
            out[gender][code] = m.group(1)
    return out


def season_rules(season: int, base: dict, hytek_dir: Path) -> dict:
    r = copy.deepcopy(base)
    src_rel = f"data/raw/hytek/{season}-area-tri-valley.htm"
    src = hytek_dir / f"{season}-area-tri-valley.htm"
    printed = printed_standards(src.read_text(encoding="latin-1")) if src.exists() else {"girls": {}, "boys": {}}
    any_printed = any(printed.values())

    r["season"] = season
    r["applied_label"] = (f"{season} rules (standards printed in {season} results; allocations {ASSUMED})"
                          if any_printed else f"{season} rules (standards and allocations {ASSUMED}; no printed source)")
    r["applies_to_seasons"] = [season]
    r["applies_to_seasons_note"] = (
        f"Generated by src/ncs_track/season_rules.py from 2026.yaml. Area->MOC at-large standards: "
        + (f"{src_rel} ({PRINTED})." if any_printed else f"{ASSUMED_NO_SOURCE}.")
        + f" All allocation numbers, league splits and other sections: {ASSUMED}."
    )
    r["sources"] = [s for s in r["sources"] if s["id"] != "transcription"] + [
        {"id": "base_rules", "path": "data/reference/rules/2026.yaml", "use": ASSUMED}]
    if any_printed:
        r["sources"].append({"id": "printed_standards", "path": src_rel, "use": PRINTED})

    std = base["area_to_moc"]["at_large"]["standards"]
    tagged = {}
    for gender, events in std.items():
        tagged[gender] = {}
        for event, mark26 in events.items():
            if printed[gender].get(event):
                tagged[gender][event] = {"mark": printed[gender][event], "source": f"{src_rel} ({PRINTED})"}
            elif any_printed:
                tagged[gender][event] = {"mark": mark26, "source": f"{ASSUMED} — not printed in {src_rel}"}
            else:
                tagged[gender][event] = {"mark": mark26, "source": ASSUMED_NO_SOURCE}
    r["area_to_moc"]["at_large"]["standards"] = tagged

    ca = r["league_to_area"]["class-a"]["at_large"]["standards"]
    for gender, events in ca.items():
        for event, mark in list(events.items()):
            events[event] = {"mark": mark, "source": ASSUMED}

    r["area_to_moc"]["scratches"]["entries_close"] = None       # 2026 date; unknown for this season
    r["area_to_moc"]["scratches"]["entries_close_note"] = "2026 deadline not applicable; not in hand for this season"
    # Section-level provenance lives in one top-level map so no rules section gains a key
    # that code iterating over it would trip on.
    r["provenance"] = {
        "area_to_moc.at_large.standards": "per standard (see each `source`)",
        "area_to_moc.auto": ASSUMED,
        "area_to_moc.fill": ASSUMED,
        "area_to_moc.at_large.eligibility": ASSUMED,
        "area_to_moc.scratches": ASSUMED,
        "league_to_area": ASSUMED + " (league splits, fills, Class A league standards)",
        "events": ASSUMED,
        "wind": ASSUMED,
        "moc_to_state": ASSUMED + " (metric (b) now uses State meet results; see docs/decisions.md)",
        "relay_4x800": ASSUMED,
    }

    d7 = r["discrepancies"]["D7"]
    d7["values"] = {"rules_in_hand": [2026], "standards_in_hand": [season] if any_printed else []}
    d7["handling"] = (f"standards {PRINTED} ({src_rel}); allocations {ASSUMED}" if any_printed
                      else f"standards and allocations {ASSUMED}")
    return r


HEADER = """\
# NCS Track & Field qualification rules — {season}
#
# GENERATED by `python -m ncs_track rules-seasons` from data/reference/rules/2026.yaml.
# Do not hand-edit; change the generator or 2026.yaml and regenerate.
#
# Area -> MOC at-large standards: {std_note}
# Every standard carries its own `source`.
# Everything else (auto spots 6/6/6/3, fill 3, league splits, Class A league standards,
# 4x800 system, wind, discrepancies): assumed from 2026 — see the top-level `provenance` map.

"""


def write_all(seasons=SEASONS) -> list[Path]:
    base = yaml.safe_load(paths.rules_path(2026).read_text())
    written = []
    for season in seasons:
        rules = season_rules(season, base, paths.RAW_HYTEK)
        printed = rules["applied_label"].startswith(f"{season} rules (standards printed")
        std_note = (f"printed in data/raw/hytek/{season}-area-tri-valley.htm" if printed
                    else "none printed this season; 2026 table used (assumed from 2026 — no printed source)")
        out = paths.rules_path(season)
        out.write_text(HEADER.format(season=season, std_note=std_note)
                       + yaml.safe_dump(rules, sort_keys=False, allow_unicode=True, width=100))
        written.append(out)
    return written
